# Copyright (c) 2021 Graphcore Ltd. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#----------------------------------------------------------------------------------
CLIP: &CLIP
  # Execution
  random_seed: 42
  encoder_start_ipu: 0
  dataloader_workers: 64
  async_dataloader: True
  file_buffer_size: 10
  ipus_per_replica: 4
  custom_ops: True
  synthetic_data: False
  profile: False
  profile_dir: profile
  executable_cache_dir: "./exe_cache"
  embedding_serialization_factor: 32
  enable_half_partials: True
  matmul_proportion: [0.2, 0.2, 0.2, 0.2]  # 0.6
  precision: '32.32'
  enable_rts: False
  wandb: True
  checkpoint_save_steps: 500
  training_steps: 8000
  batches_per_step: 10
  replication_factor: 1
  gradient_accumulation: 10

  # Dataset
  image_path: "/localdata/minghongc/datasets/Flickr8k/Flicker8k_Dataset"
  captions_path: "/localdata/minghongc/datasets/Flickr8k"
  batch_size: 14
  epochs: 5
  dataset: multimodal
  checkpoint_file: "/localdata/minghongc/workspace/CLIP/output/ckpt/multimodal_vit_L_12_H_12_W_768_patch_32_transformer_L_12_H_8_W_512_len_77_epoch_1.pt"
  checkpoint_dir: "output/ckpt"
  restore: False

  # Optimizer
  optimizer: Adam
  beta1: 0.9
  beta2: 0.98
  eps: 1e-6
  weight_decay: 0.2
  lr_warmup: 0.28
  warmup_steps: 2000
  lr_schedule: consine
  learning_rate: 1e-5
  loss_scaling: 1.0
  momentum : 0.9

  # CLIP
  embed_dim: 512
  transformer_width: 512
  transformer_heads: 8
  transformer_layers: 12
  context_length: 77

  vision_width: 768
  vision_layers: 12
  vision_heads: 12
  vision_patch_size: 32
  grid_size: 7
  image_resolution: 224

  vocab_size: 49408
  layer_norm_eps: 0.001

  truncate: True

#----------------------------------------------------------------------------------

